# Generated by Django 3.2 on 2024-02-17 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100, verbose_name='День недели (Например: Понедельник (21.02))')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('task', models.TextField(verbose_name='Задачи на день')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец заметок')),
            ],
            options={
                'verbose_name': 'Заметку',
                'verbose_name_plural': 'Заметки',
            },
        ),
    ]
